#!/usr/bin/env bash
# This script transfers a file from our client to a server

# Check if exactly 4 arguments are provided ($# show the no. of args)
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to variables for clarity
FILE="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Transfer the file using scp with strict host key checking disabled
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE" "$USERNAME@$SERVER_IP:~/"
