#!/usr/bin/env bash
# Install Nginx and configure a 301 redirect for /redirect_me

# Update package lists and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Define the redirection configuration as a variable
REDIRECT_CONFIG="location = /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }"

# Insert the redirection configuration into the Nginx configuration file
sudo sed -i "/server_name _;/a $REDIRECT_CONFIG" /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
