#!/usr/bin/env bash
# 0-custom_http_response_header
# Configures Nginx to include a custom HTTP header "X-Served-By" with the hostname

# Update and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Set ownership of /var/www
sudo chown -R ubuntu:ubuntu /var/www

# Replace default index page with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Get the hostname of the server
HOSTNAME=$(hostname)

# Add the custom header to the Nginx configuration
sudo sed -i "/server_name _;/a \\\n    add_header X-Served-By \"$HOSTNAME\";" /etc/nginx/sites-available/default

# Add the redirection rule using sed
ADD301_REDIRECT="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 perman    ent;"
CONFIG_FILE="/etc/nginx/sites-available/default"
sudo sed -i "30i $ADD301_REDIRECT" "$CONFIG_FILE"

# Create a custom 404 page with the required content
echo -n "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Set permissions for the 404.html file
sudo chmod 644 /var/www/html/404.html

#Configure Nginx to use the custom 404 page
CONFIG_FILE="/etc/nginx/sites-available/default"
CUSTOM_404="\\\terror_page 404 /404.html;"

# Insert the custom 404 configuration in the server block after 'server_name _;'
sudo sed -i "/server_name _;/a $CUSTOM_404" "$CONFIG_FILE"

# Restart Nginx to apply changes
sudo nginx -t
sudo service nginx restart
