#!/usr/bin/env bash
# Script to install and configure HAProxy on Ubuntu

# Update and install HAProxy
sudo apt-get update -y
sudo apt-get install -y haproxy

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
# Frontend for incoming connections
frontend front_server
        bind *:80
        default_backend back_servers

# Backend for routing traffic
backend back_servers
        balance roundrobin
        server 806536-web-01 34.203.75.109:80 check
        server 806536-web-02 3.86.13.56:80 check
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
sudo service haproxy restart
