#!/usr/bin/env bash
# This script debugs an Ubuntu container's Nginx installation

# Ensure Nginx is installed
apt-get update -y && apt-get install -y nginx

# Deleting the current nginx configurations if available
rm /etc/nginx/sites-enabled/default

# Reconfiguring nginx by linking to sites-enabled
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx to apply the configuration
service nginx restart
