#!/usr/bin/env bash
# This script debugs an Ubuntu container's Nginx installation
rm /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
