#!/bin/bash
ls -a1 --group-directories-first | awk '{if ($0 == "." || $0 == "..") print $0; else if (system("[ -d \"" $0 "\" ]") == 0) print $0 "/"; else print $0}' | sort -f | awk '{printf("%s, ", $0)} END {print ""}' | sed 's/, $/\n/'
