#!/usr/bin/env bash
# This Bash script displays lines containing the bash word
# shellcheck disable=SC2009# shellcheck disable=SC2009# shellcheck disable=SC2009
ps -e --forest -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command | grep bash
