#!/usr/bin/env bash
# kills the process 7-highlander.

# Get the PID of the 7-highlander process
pid=$(pgrep -f "7-highlander")

# Check if the process is running
if [ -n "$pid" ]; then
	# Kill the process and print "Killed"
	kill -9 "$pid"
fi
