#!/usr/bin/env bash
# This script displays the username, user ID, and home directory from the /etc/passwd file

while IFS=: read -r username _ user_id _ _ home_dir _; do
    echo "$username:$user_id:$home_dir"
done < /etc/passwd
