#!/usr/bin/env bash
# Uses while loop and if, elif and else statements to dispay 10 elements.
#	display "bad luck" for the fourth iteration
#	display "good luck" for the eighth iteration
#	displays "Best School" for the rest of the iterations.

count=1
while [ $count -le 10 ]
do
	if [ $count -eq 4 ]; then
		echo "bad luck"
	elif [ $count -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	count=$((count + 1))
done
