#!/usr/bin/env bash
# The bash script displays:
#	The content of the current directory
#	In a list format
#	Where only the part of the name after the first dash is displayed (refer to the example)

for file in *
do
	new_name="${file#*-}"

	echo "$new_name"
done
