#!/usr/bin/env bash

# Enable UFW NAT for port forwarding
sudo sed -i '/^*filter/i \
*nat\n\
:PREROUTING ACCEPT [0:0]\n\
-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80\n\
COMMIT\n' /etc/ufw/before.rules

# Enable packet forwarding
sudo sed -i 's/#net\/ipv4\/ip_forward=1/net\/ipv4\/ip_forward=1/' /etc/ufw/sysctl.conf

# Allow traffic on port 8080
sudo ufw allow 8080/tcp

# Restart UFW to apply changes
sudo ufw reload
