#!/usr/bin/env bash
# This script displays all active IPv4 IP addresses on the machine

# Use the 'ip' command to show IPv4 addresses, filtering for inet (IPv4) entries
ip -4 -o addr show | awk '{print $4}' | cut -d'/' -f1 
