#!/usr/bin/env bash
# Fix Nginx to run as nginx user and listen on port 8080
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/listen 80/listen 8080/" /etc/nginx/sites-available/default
sudo service nginx stop
sudo fuser -k 8080/tcp
sudo -u nginx /usr/sbin/nginx
