#!/usr/bin/env bash
# This sript shortes script 1-run_nginx_as_nginx to 7 or less lines
sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 /listen 8080 /' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 /listen \[::\]:8080 /' /etc/nginx/sites-available/default
service nginx restart
